SELECT 'PPCD' PPCD, OFFER.OFFER_ID, CHARGE_CODE.CHARGE_CODE, CHARGE_CODE.DSCR CHARGE_CODE_DESC
FROM FY_TB_PBK_OFFER OFFER, FY_TB_PBK_OFFER_PACKAGE OFFER_PACKAGE, FY_TB_PBK_PACKAGE_RC PACKAGE_RC, FY_TB_PBK_CHARGE_CODE CHARGE_CODE
WHERE OFFER.OFFER_ID = OFFER_PACKAGE.OFFER_ID
AND OFFER_PACKAGE.PKG_ID = PACKAGE_RC.PKG_ID
AND PACKAGE_RC.CHARGE_CODE = CHARGE_CODE.CHARGE_CODE
AND OFFER.OFFER_TYPE ='PP'