select 
'RINS' RINS,
'' BE_ID, 
PLMN_SENDER, 
TO_CHAR(EFFECTIVE_DATE,'YYYYMMDD') EFFECTIVE_DATE,
'' PROVIDER_ID,
'' COUNTRY_CODE,
'' TAX_DEDUCTION, 
'' EXCHANGE_CODE, 
'' PROVIDER_STATUS,
'' ROAMING_ZONE_INDICATOR, 
DESCRIPTION,
TO_CHAR(EXPIRATION_DATE,'YYYYMMDD') EXPIRATION_DATE
from BL9_INCOL_SID