SELECT 'RPYS' RPYS, AR1_PAYMENT_SOURCE.SOURCE_ID, AR1_GENERIC_CODES.DESCRIPTION, AR1_PAYMENT_SOURCE.SOURCE_TYPE 
FROM AR1_GENERIC_CODES, AR1_PAYMENT_SOURCE 
WHERE AR1_PAYMENT_SOURCE.SOURCE_ID = AR1_GENERIC_CODES.CODE