SELECT 'BIDS' DUMMY,
C.PKG_ID SOC_CD,
C.PKG_NAME SOC_NAME,
C.PKG_TYPE SOC_TYPE,
'' SERVICE_LEVEL,
C.PKG_PRIORITY PRIORITY,
C.BILL_CATEGORY DISCOUNT_CATEGORY,
'L' SUBSCRIBER_TYPE,
'Net' AMOUNT_TYPE
FROM  FY_TB_PBK_OFFER A, FY_TB_PBK_OFFER_PACKAGE B, FY_TB_PBK_PACKAGE C
WHERE A.OFFER_ID=B.OFFER_ID
AND B.PKG_ID = C.PKG_ID
AND C.PKG_TYPE='D'
AND A.PRODUCT_TYPE in ('ALL','L')
UNION
SELECT 'BIDS' DUMMY,
C.PKG_ID SOC_CD,
C.PKG_NAME SOC_NAME,
C.PKG_TYPE SOC_TYPE,
'' SERVICE_LEVEL,
C.PKG_PRIORITY PRIORITY,
C.BILL_CATEGORY DISCOUNT_CATEGORY,
'G' SUBSCRIBER_TYPE,
'Gross' AMOUNT_TYPE
FROM  FY_TB_PBK_OFFER A, FY_TB_PBK_OFFER_PACKAGE B, FY_TB_PBK_PACKAGE C
WHERE A.OFFER_ID=B.OFFER_ID
AND B.PKG_ID = C.PKG_ID
AND C.PKG_TYPE='D'
AND A.PRODUCT_TYPE <> 'L'