select 'VMSG' DUMMY, 
VC.ALIAS MESSAGETYPE,  
VC.FILE_NAME CONTEXT, 
VC.PRIORITY
from FF9_VIP_CONFIG VC , FY_TB_BL_BILL_CNTRL BC
where VC.VIP_DEFAULT='Y'
and VC.CYCLE_YEAR= to_char(BC.BILL_DATE,'YYYY')
and VC.CYCLE_MONTH=to_char(BC.BILL_DATE,'fmMM')
AND BC.BILL_SEQ = ${billSeq}