SELECT  DECODE(CD.TRN_MTHD,NULL, D.FILE_NME, SUBSTR(CD.TRN_TARGET,INSTR(CD.TRN_TARGET,'/'))||SUBSTR(D.FILE_NME, INSTR(D.FILE_NME,'/',-1) )) FILE_NME
FROM FY_TB_DIO_CONF_DTL CD, FY_TB_DIO_CNTRL C, FY_TB_DIO_CNTRL_DTL D
WHERE C.CONFIRM_ID IN (
    SELECT MAX(CONFIRM_ID) FROM  FY_TB_DIO_CNTRL
    WHERE CNTRL_SEQ = CNTRL_SEQ
    AND CONF_DTL_SEQ IN(53,54,55,56,57,58,59,60)
    AND BILL_SEQ = ${billSeq}
    AND PROCESS_NO = ${processNo}
    AND ACCT_GROUP = ${acctGroup}
    AND PROC_TYPE =${procType}
    GROUP BY CONF_DTL_SEQ
)
AND C.CONF_DTL_SEQ = CD.CONF_DTL_SEQ
AND C.CNTRL_SEQ = D.CNTRL_SEQ
AND C.STATUS = 'S'
AND C.CONF_DTL_SEQ IN(53,54,55,56,57,58,59,60)
ORDER BY D.FILE_NME